export const filterStyles = {
  container: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "start",
    transition: "all 0.3s",
    position: "sticky",
    zIndex: "3",
    border: "1px solid #ddd5",
    borderRadius: "0 1rem 0 0",
  },
  icon: {
    fontSize: "1.5rem",
    fontWeight: "900",
    paddingInline: "0.6rem",
    borderRadius: "50%",
  },
  iconWrapper: {
    display: "flex",
    justifyContent: "start",
    alignItems: "center",
    width: "100%",
    transition: "all 1s",
  },
  insideWrapper: {
    width: "100%",
    transition: "all 0.3s",
    // display: open ? "flex" : "none",
    flexDirection: "column",
    rowGap: "10px",
    paddingInline: "1rem",
  },
  grid: {
    container: { width: "100%", columnGap: "10px", rowGap: "10px" },
  },
  textField: { width: "100%", cursor: "pointer" },
  buttonWrapper: {
    display: "flex",
    columnGap: "5px",
    justifyContent: "end",
    paddingInline: "3rem",
    paddingBottom: "0.5rem",
  },
};
