import Dashboard from "./components/dashboard";
import Providers from "./redux/provider";
import XToastContainer from "./helpers/toastContainer";

export const metadata = {
  title: "Attensam Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Dashboard children={children} />
          <XToastContainer />
        </Providers>
      </body>
    </html>
  );
}
